using Lisa.AI.OpenAIModels.BaseCompletionModels;

namespace Lisa.AI.OpenAIModels.ChatCompletionModels;

/// <summary>
/// Details of a completion choice in a streaming response
/// </summary>
public class ChatCompletionChunkResponseChoice : BaseCompletionResponseChoice
{
    /// <summary>
    /// Incremental chat completion generated by the streaming model response
    /// </summary>
    public ChatCompletionMessage? delta { get; set; } = new();
}
