using Lisa.AI.OpenAIModels.BaseCompletionModels;

namespace Lisa.AI.OpenAIModels.ChatCompletionModels;

/// <summary>
/// A single choice in the completion response
/// </summary>
public class ChatCompletionResponseChoice : BaseCompletionResponseChoice
{
    /// <summary>
    /// Message generated by the model for the chat completion
    /// </summary>
    public ChatCompletionMessage message { get; set; } = new();
}
