using Lisa.AI.OpenAIModels.BaseCompletionModels;

namespace Lisa.AI.OpenAIModels.CompletionModels;

/// <summary>
/// A single choice in the completion response
/// </summary>
public class CompletionResponseChoice : BaseCompletionResponseChoice
{
    /// <summary>
    /// Text generated by the model for the completion
    /// </summary>
    public string? text { get; set; } = string.Empty;
}
